# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "C:/Users/asene/projects/sturdy-engine/data/models")
v <- vetiver_pin_read(b, "payroll-model", version = "20250226T194040Z-da749")

#* @plumber
function(pr) {
  pr %>% vetiver_api(v)
}
